import type { Place } from "./types";

export const SEED_PLACES: Place[] = [
  {
    id: "morning-rituals",
    name: "Morning Rituals",
    vibe: "Soft light, ceramic cups, and no rush.",
    neighborhood: "West Village",
    tags: ["Quiet", "Cafe", "Walkable", "Solo"],
    statuses: ["Quiet", "Solo Friendly"],
    coordinates: { lng: -74.0048, lat: 40.7335 },
    bestFor: ["morning"],
    openHour: 6,
    closeHour: 16,
  },
  {
    id: "lowline-espresso",
    name: "Lowline Espresso",
    vibe: "Sunlit windows and soft jazz at opening hours.",
    neighborhood: "Lower East Side",
    tags: ["Cafe", "Solo", "Walkable"],
    statuses: ["Morning Favorite", "Walkable"],
    coordinates: { lng: -73.9871, lat: 40.7186 },
    bestFor: ["morning", "afternoon"],
    openHour: 7,
    closeHour: 18,
  },
  {
    id: "eighth-street-bread",
    name: "Eighth Street Bread",
    vibe: "Buttery pastries, paperbacks, and a slow counter line.",
    neighborhood: "East Village",
    tags: ["Cafe", "Weekend", "Quiet"],
    statuses: ["Weekend Friendly", "Open Early"],
    coordinates: { lng: -73.9879, lat: 40.7272 },
    bestFor: ["morning"],
    openHour: 6,
    closeHour: 14,
  },
  {
    id: "hudson-step",
    name: "Hudson Step",
    vibe: "Airy river walk with low traffic and long views.",
    neighborhood: "Hudson River Park",
    tags: ["Walkable", "Quiet", "Weekend"],
    statuses: ["Open Air", "Quiet"],
    coordinates: { lng: -74.0109, lat: 40.7398 },
    bestFor: ["morning", "afternoon", "dusk"],
    openHour: 5,
    closeHour: 22,
  },
  {
    id: "amber-library-bar",
    name: "Amber Library Bar",
    vibe: "Warm wood, low conversation, long late-night sessions.",
    neighborhood: "NoMad",
    tags: ["Quiet", "Late Night", "Solo"],
    statuses: ["Open Late", "Quiet"],
    coordinates: { lng: -73.9873, lat: 40.7441 },
    bestFor: ["dusk", "night"],
    openHour: 16,
    closeHour: 2,
  },
  {
    id: "neon-noodle-room",
    name: "Neon Noodle Room",
    vibe: "Steamy bowls and neon reflections after 10 PM.",
    neighborhood: "Chinatown",
    tags: ["Late Night", "Walkable", "Weekend"],
    statuses: ["Open Late", "After Dark"],
    coordinates: { lng: -73.9971, lat: 40.7158 },
    bestFor: ["night"],
    openHour: 17,
    closeHour: 3,
  },
  {
    id: "orchard-film-club",
    name: "Orchard Film Club",
    vibe: "Intimate screenings with editorial curation.",
    neighborhood: "Lower East Side",
    tags: ["Weekend", "Solo", "Late Night"],
    statuses: ["Curated", "Open Late"],
    coordinates: { lng: -73.9889, lat: 40.7218 },
    bestFor: ["dusk", "night"],
    openHour: 14,
    closeHour: 1,
  },
  {
    id: "sunset-roof",
    name: "Sunset Roof",
    vibe: "Pink sky, warm breeze, and low-key lounge beats.",
    neighborhood: "Williamsburg",
    tags: ["Weekend", "Late Night"],
    statuses: ["Golden Hour", "Best at Dusk"],
    coordinates: { lng: -73.9566, lat: 40.7184 },
    bestFor: ["dusk"],
    openHour: 15,
    closeHour: 0,
  },
  {
    id: "canal-glasshouse",
    name: "Canal Glasshouse",
    vibe: "Gallery-cafe hybrid with afternoon natural light.",
    neighborhood: "SoHo",
    tags: ["Cafe", "Weekend", "Walkable"],
    statuses: ["Sunlit", "Open Studio"],
    coordinates: { lng: -74.0011, lat: 40.7231 },
    bestFor: ["afternoon", "dusk"],
    openHour: 10,
    closeHour: 20,
  },
  {
    id: "quiet-archive",
    name: "Quiet Archive",
    vibe: "A reading room hidden behind a vintage storefront.",
    neighborhood: "Tribeca",
    tags: ["Quiet", "Solo", "Weekend"],
    statuses: ["Quiet", "Solo Friendly"],
    coordinates: { lng: -74.0082, lat: 40.7199 },
    bestFor: ["morning", "afternoon"],
    openHour: 9,
    closeHour: 19,
  },
  {
    id: "harbor-plates",
    name: "Harbor Plates",
    vibe: "Daytime brunch shifts into amber-lit dinner service.",
    neighborhood: "Seaport",
    tags: ["Weekend", "Walkable", "Late Night"],
    statuses: ["All Day", "Good for Groups"],
    coordinates: { lng: -74.0035, lat: 40.7066 },
    bestFor: ["afternoon", "dusk", "night"],
    openHour: 9,
    closeHour: 1,
  },
  {
    id: "cedar-court",
    name: "Cedar Court",
    vibe: "Plant-filled courtyard, low-volume playlists, and long lunch.",
    neighborhood: "Flatiron",
    tags: ["Cafe", "Walkable", "Quiet"],
    statuses: ["Outdoor Seating", "Calm"],
    coordinates: { lng: -73.9898, lat: 40.7414 },
    bestFor: ["morning", "afternoon"],
    openHour: 8,
    closeHour: 19,
  },
  {
    id: "afterline-ramen",
    name: "Afterline Ramen",
    vibe: "Steady late service and rich broth after midnight.",
    neighborhood: "East Village",
    tags: ["Late Night", "Solo", "Walkable"],
    statuses: ["Open Late", "Counter Seating"],
    coordinates: { lng: -73.9832, lat: 40.7284 },
    bestFor: ["night"],
    openHour: 18,
    closeHour: 4,
  },
  {
    id: "park-circle",
    name: "Park Circle",
    vibe: "A loop for long walks when the city slows down.",
    neighborhood: "Prospect Park",
    tags: ["Walkable", "Quiet", "Weekend"],
    statuses: ["Open Air", "Best at Dawn"],
    coordinates: { lng: -73.968, lat: 40.6604 },
    bestFor: ["morning", "dusk"],
    openHour: 5,
    closeHour: 22,
  },
  {
    id: "lantern-bookshop",
    name: "Lantern Bookshop",
    vibe: "Independent shelves with tea service after sunset.",
    neighborhood: "Fort Greene",
    tags: ["Quiet", "Solo", "Weekend"],
    statuses: ["Curated", "Calm"],
    coordinates: { lng: -73.9739, lat: 40.6894 },
    bestFor: ["afternoon", "dusk"],
    openHour: 11,
    closeHour: 21,
  },
  {
    id: "north-ferry-late",
    name: "North Ferry Late",
    vibe: "Dockside city lights and quiet benches after 10 PM.",
    neighborhood: "Battery Park",
    tags: ["Late Night", "Quiet", "Walkable"],
    statuses: ["After Dark", "Quiet"],
    coordinates: { lng: -74.0161, lat: 40.7013 },
    bestFor: ["night"],
    openHour: 18,
    closeHour: 2,
  },
  {
    id: "civic-sunroom",
    name: "Civic Sunroom",
    vibe: "Gold-hour atrium with natural reverb and coffee flights.",
    neighborhood: "Civic Center",
    tags: ["Cafe", "Weekend", "Solo"],
    statuses: ["Sunlit", "Popular"],
    coordinates: { lng: -73.9991, lat: 40.7138 },
    bestFor: ["afternoon"],
    openHour: 10,
    closeHour: 18,
  },
  {
    id: "silent-vinyl",
    name: "Silent Vinyl",
    vibe: "Listening room with late sets and velvet seating.",
    neighborhood: "Greenpoint",
    tags: ["Late Night", "Solo", "Weekend"],
    statuses: ["Open Late", "Editorial Curation"],
    coordinates: { lng: -73.9496, lat: 40.7316 },
    bestFor: ["dusk", "night"],
    openHour: 17,
    closeHour: 2,
  },
  {
    id: "meadow-kiosk",
    name: "Meadow Kiosk",
    vibe: "Open-air coffee and easy strolls near the lawn.",
    neighborhood: "Central Park South",
    tags: ["Walkable", "Cafe", "Weekend"],
    statuses: ["Open Air", "Casual"],
    coordinates: { lng: -73.9741, lat: 40.7666 },
    bestFor: ["morning", "afternoon"],
    openHour: 7,
    closeHour: 19,
  },
  {
    id: "atlas-nocturne",
    name: "Atlas Nocturne",
    vibe: "Cocktail den with midnight jazz and dim brass lighting.",
    neighborhood: "Chelsea",
    tags: ["Late Night", "Weekend"],
    statuses: ["Open Late", "Live Set"],
    coordinates: { lng: -74.0015, lat: 40.7481 },
    bestFor: ["night"],
    openHour: 19,
    closeHour: 3,
  },
  {
    id: "linden-terrace",
    name: "Linden Terrace",
    vibe: "A warm-hour terrace for long conversations.",
    neighborhood: "Brooklyn Heights",
    tags: ["Weekend", "Walkable", "Quiet"],
    statuses: ["Golden Hour", "Outdoor"],
    coordinates: { lng: -73.9957, lat: 40.6962 },
    bestFor: ["afternoon", "dusk"],
    openHour: 12,
    closeHour: 23,
  },
  {
    id: "evening-atelier",
    name: "Evening Atelier",
    vibe: "Design shop by day, wine bar by evening.",
    neighborhood: "SoHo",
    tags: ["Weekend", "Late Night", "Solo"],
    statuses: ["Hybrid Space", "Open Late"],
    coordinates: { lng: -74.0018, lat: 40.7247 },
    bestFor: ["dusk", "night"],
    openHour: 13,
    closeHour: 1,
  },
  {
    id: "riverside-steps",
    name: "Riverside Steps",
    vibe: "Quiet sunset perch with long river glow.",
    neighborhood: "Upper West Side",
    tags: ["Quiet", "Walkable", "Weekend"],
    statuses: ["Best at Dusk", "Open Air"],
    coordinates: { lng: -73.9896, lat: 40.8012 },
    bestFor: ["dusk", "night"],
    openHour: 6,
    closeHour: 23,
  },
  {
    id: "mercer-afterhours",
    name: "Mercer Afterhours",
    vibe: "Late plates and a calm bar line past midnight.",
    neighborhood: "NoHo",
    tags: ["Late Night", "Solo", "Walkable"],
    statuses: ["Open Late", "Low Noise"],
    coordinates: { lng: -73.9959, lat: 40.7277 },
    bestFor: ["night"],
    openHour: 18,
    closeHour: 4,
  },
  {
    id: "mission-drift",
    name: "Mission Drift",
    vibe: "Late espresso, vinyl corners, and warm lamps.",
    neighborhood: "Mission District, San Francisco",
    tags: ["Cafe", "Solo", "Late Night"],
    statuses: ["Open Late", "Solo Friendly"],
    coordinates: { lng: -122.4193, lat: 37.7597 },
    bestFor: ["dusk", "night"],
    openHour: 9,
    closeHour: 1,
  },
  {
    id: "hayes-softlight",
    name: "Hayes Softlight",
    vibe: "Quiet tables and a clean afternoon glow.",
    neighborhood: "Hayes Valley, San Francisco",
    tags: ["Quiet", "Cafe", "Walkable"],
    statuses: ["Quiet", "Walkable"],
    coordinates: { lng: -122.4242, lat: 37.7764 },
    bestFor: ["morning", "afternoon"],
    openHour: 7,
    closeHour: 19,
  },
  {
    id: "north-beach-steps",
    name: "North Beach Steps",
    vibe: "Hilltop walk with city lights after sunset.",
    neighborhood: "North Beach, San Francisco",
    tags: ["Walkable", "Weekend", "Quiet"],
    statuses: ["Open Air", "Best at Dusk"],
    coordinates: { lng: -122.4101, lat: 37.8044 },
    bestFor: ["dusk", "night"],
    openHour: 6,
    closeHour: 23,
  },
  {
    id: "echo-park-glass",
    name: "Echo Park Glass",
    vibe: "Soft daytime windows and long-reading corners.",
    neighborhood: "Echo Park, Los Angeles",
    tags: ["Cafe", "Quiet", "Solo"],
    statuses: ["Sunlit", "Calm"],
    coordinates: { lng: -118.2604, lat: 34.0782 },
    bestFor: ["morning", "afternoon"],
    openHour: 7,
    closeHour: 20,
  },
  {
    id: "arts-district-after",
    name: "Arts District After",
    vibe: "Industrial streets with warm late-hour energy.",
    neighborhood: "Arts District, Los Angeles",
    tags: ["Late Night", "Weekend", "Walkable"],
    statuses: ["Open Late", "After Dark"],
    coordinates: { lng: -118.2349, lat: 34.0398 },
    bestFor: ["dusk", "night"],
    openHour: 12,
    closeHour: 2,
  },
  {
    id: "venice-bluehour",
    name: "Venice Bluehour",
    vibe: "Sea breeze, boardwalk glow, and casual stops.",
    neighborhood: "Venice, Los Angeles",
    tags: ["Walkable", "Weekend", "Late Night"],
    statuses: ["Open Air", "Golden Hour"],
    coordinates: { lng: -118.4695, lat: 33.985 },
    bestFor: ["afternoon", "dusk", "night"],
    openHour: 10,
    closeHour: 0,
  },
  {
    id: "wicker-morning-room",
    name: "Wicker Morning Room",
    vibe: "Clean coffee bar with calm early city rhythm.",
    neighborhood: "Wicker Park, Chicago",
    tags: ["Cafe", "Quiet", "Solo"],
    statuses: ["Open Early", "Quiet"],
    coordinates: { lng: -87.6763, lat: 41.9088 },
    bestFor: ["morning"],
    openHour: 6,
    closeHour: 17,
  },
  {
    id: "river-north-late",
    name: "River North Late",
    vibe: "Night kitchens and low-volume after-hours seats.",
    neighborhood: "River North, Chicago",
    tags: ["Late Night", "Weekend", "Solo"],
    statuses: ["Open Late", "Low Noise"],
    coordinates: { lng: -87.6301, lat: 41.8923 },
    bestFor: ["night"],
    openHour: 17,
    closeHour: 3,
  },
  {
    id: "lincoln-green-loop",
    name: "Lincoln Green Loop",
    vibe: "Tree-lined walks and a soft afternoon pace.",
    neighborhood: "Lincoln Park, Chicago",
    tags: ["Walkable", "Quiet", "Weekend"],
    statuses: ["Open Air", "Calm"],
    coordinates: { lng: -87.6376, lat: 41.9236 },
    bestFor: ["morning", "afternoon", "dusk"],
    openHour: 6,
    closeHour: 22,
  },
  {
    id: "capitol-hill-soft",
    name: "Capitol Hill Soft",
    vibe: "Notebook tables and mellow daytime playlists.",
    neighborhood: "Capitol Hill, Seattle",
    tags: ["Cafe", "Solo", "Quiet"],
    statuses: ["Solo Friendly", "Calm"],
    coordinates: { lng: -122.3207, lat: 47.623 },
    bestFor: ["morning", "afternoon"],
    openHour: 7,
    closeHour: 19,
  },
  {
    id: "fremont-night-dock",
    name: "Fremont Night Dock",
    vibe: "Water reflections and quiet benches after dark.",
    neighborhood: "Fremont, Seattle",
    tags: ["Late Night", "Walkable", "Quiet"],
    statuses: ["After Dark", "Open Air"],
    coordinates: { lng: -122.3493, lat: 47.6511 },
    bestFor: ["night"],
    openHour: 17,
    closeHour: 2,
  },
  {
    id: "ballard-sunset-room",
    name: "Ballard Sunset Room",
    vibe: "Golden-hour decks and unhurried small plates.",
    neighborhood: "Ballard, Seattle",
    tags: ["Weekend", "Walkable", "Late Night"],
    statuses: ["Golden Hour", "Open Late"],
    coordinates: { lng: -122.3844, lat: 47.6689 },
    bestFor: ["dusk", "night"],
    openHour: 13,
    closeHour: 1,
  },
  {
    id: "south-end-quiet",
    name: "South End Quiet",
    vibe: "Brick streets, espresso, and slow morning light.",
    neighborhood: "South End, Boston",
    tags: ["Quiet", "Cafe", "Walkable"],
    statuses: ["Quiet", "Walkable"],
    coordinates: { lng: -71.0766, lat: 42.3412 },
    bestFor: ["morning", "afternoon"],
    openHour: 7,
    closeHour: 18,
  },
  {
    id: "seaport-afterhours",
    name: "Seaport Afterhours",
    vibe: "Harbor lights and late bites past midnight.",
    neighborhood: "Seaport, Boston",
    tags: ["Late Night", "Weekend", "Walkable"],
    statuses: ["Open Late", "After Dark"],
    coordinates: { lng: -71.0418, lat: 42.3517 },
    bestFor: ["night"],
    openHour: 16,
    closeHour: 2,
  },
  {
    id: "cambridge-blue",
    name: "Cambridge Blue",
    vibe: "Library mood by day, warm dining by evening.",
    neighborhood: "Kendall Square, Cambridge",
    tags: ["Solo", "Weekend", "Cafe"],
    statuses: ["Hybrid Space", "Curated"],
    coordinates: { lng: -71.0868, lat: 42.3626 },
    bestFor: ["afternoon", "dusk"],
    openHour: 9,
    closeHour: 22,
  },
  {
    id: "east-austin-glow",
    name: "East Austin Glow",
    vibe: "Colorful streets and easy late-evening energy.",
    neighborhood: "East Austin, Austin",
    tags: ["Late Night", "Weekend", "Walkable"],
    statuses: ["Open Late", "Popular"],
    coordinates: { lng: -97.7182, lat: 30.2649 },
    bestFor: ["dusk", "night"],
    openHour: 11,
    closeHour: 2,
  },
  {
    id: "zilker-morning",
    name: "Zilker Morning",
    vibe: "Green park loops and bright early air.",
    neighborhood: "Zilker, Austin",
    tags: ["Walkable", "Quiet", "Weekend"],
    statuses: ["Open Air", "Best at Dawn"],
    coordinates: { lng: -97.7729, lat: 30.2669 },
    bestFor: ["morning", "afternoon"],
    openHour: 6,
    closeHour: 21,
  },
  {
    id: "south-congress-soft",
    name: "South Congress Soft",
    vibe: "Slow cafes and long-hour sidewalk wandering.",
    neighborhood: "South Congress, Austin",
    tags: ["Cafe", "Walkable", "Solo"],
    statuses: ["Walkable", "Sunlit"],
    coordinates: { lng: -97.7483, lat: 30.2497 },
    bestFor: ["afternoon", "dusk"],
    openHour: 8,
    closeHour: 23,
  },
  {
    id: "denver-rino-late",
    name: "RiNo Late",
    vibe: "Murals, night kitchens, and low neon glow.",
    neighborhood: "RiNo, Denver",
    tags: ["Late Night", "Weekend", "Walkable"],
    statuses: ["After Dark", "Open Late"],
    coordinates: { lng: -104.9782, lat: 39.7612 },
    bestFor: ["dusk", "night"],
    openHour: 15,
    closeHour: 2,
  },
  {
    id: "denver-cap-hill-calm",
    name: "Cap Hill Calm",
    vibe: "Neighborhood coffee and quiet corners.",
    neighborhood: "Capitol Hill, Denver",
    tags: ["Cafe", "Quiet", "Solo"],
    statuses: ["Calm", "Solo Friendly"],
    coordinates: { lng: -104.9762, lat: 39.7336 },
    bestFor: ["morning", "afternoon"],
    openHour: 7,
    closeHour: 19,
  },
  {
    id: "miami-wynwood-dusk",
    name: "Wynwood Dusk",
    vibe: "Art blocks and warm evening movement.",
    neighborhood: "Wynwood, Miami",
    tags: ["Weekend", "Walkable", "Late Night"],
    statuses: ["Golden Hour", "Open Late"],
    coordinates: { lng: -80.1989, lat: 25.8014 },
    bestFor: ["afternoon", "dusk", "night"],
    openHour: 11,
    closeHour: 1,
  },
  {
    id: "miami-design-mornings",
    name: "Design Mornings",
    vibe: "Bright cafes and easy solo starts.",
    neighborhood: "Design District, Miami",
    tags: ["Cafe", "Solo", "Weekend"],
    statuses: ["Sunlit", "Solo Friendly"],
    coordinates: { lng: -80.1929, lat: 25.8135 },
    bestFor: ["morning", "afternoon"],
    openHour: 8,
    closeHour: 20,
  },
  {
    id: "portland-eastside-quiet",
    name: "Eastside Quiet",
    vibe: "Bookish cafes and relaxed neighborhood pace.",
    neighborhood: "Central Eastside, Portland",
    tags: ["Quiet", "Cafe", "Solo"],
    statuses: ["Quiet", "Curated"],
    coordinates: { lng: -122.6604, lat: 45.5152 },
    bestFor: ["morning", "afternoon"],
    openHour: 7,
    closeHour: 18,
  },
  {
    id: "portland-pearl-night",
    name: "Pearl Night Walk",
    vibe: "Gallery blocks and calm late-night streets.",
    neighborhood: "Pearl District, Portland",
    tags: ["Late Night", "Walkable", "Quiet"],
    statuses: ["After Dark", "Open Air"],
    coordinates: { lng: -122.6846, lat: 45.5287 },
    bestFor: ["dusk", "night"],
    openHour: 16,
    closeHour: 1,
  },
  {
    id: "providence-riverwalk-dawn",
    name: "Providence Riverwalk",
    vibe: "Soft morning light and a quiet downtown loop.",
    neighborhood: "Downtown, Providence",
    tags: ["Walkable", "Quiet", "Weekend"],
    statuses: ["Open Air", "Best at Dawn"],
    coordinates: { lng: -71.4128, lat: 41.8245 },
    bestFor: ["morning", "afternoon"],
    openHour: 6,
    closeHour: 22,
  },
  {
    id: "providence-federal-calm",
    name: "Federal Calm",
    vibe: "Neighborhood espresso and low-volume afternoons.",
    neighborhood: "Federal Hill, Providence",
    tags: ["Cafe", "Solo", "Quiet"],
    statuses: ["Calm", "Solo Friendly"],
    coordinates: { lng: -71.4263, lat: 41.8218 },
    bestFor: ["morning", "afternoon", "dusk"],
    openHour: 7,
    closeHour: 21,
  },
  {
    id: "providence-college-hill-late",
    name: "College Hill Late",
    vibe: "Warm lamps, easy bites, and after-dark student energy.",
    neighborhood: "College Hill, Providence",
    tags: ["Late Night", "Walkable", "Weekend"],
    statuses: ["Open Late", "After Dark"],
    coordinates: { lng: -71.4011, lat: 41.8279 },
    bestFor: ["dusk", "night"],
    openHour: 11,
    closeHour: 1,
  },
];
